version: '3.3'
services:
  feishu-chatgpt:
    container_name: feishu-chatgpt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000/tcp"
    # volumes:
    #   - ./code/config.yaml:/app/config.yaml:ro
    environment:
      - APP_ID=cli_a47a7a06d8b8d00d
      - APP_SECRET=lopWDiubxy9qCF3z6UAhVgIpToVVKvty
      - APP_ENCRYPT_KEY=17Smquq7RcoIuR0Wsy08TftIZLqkBkD4
      - APP_VERIFICATION_TOKEN=WY3oFKdWIvZL3B1MNpRJNgwbaZMkYgTa
      # 请确保和飞书应用管理平台中的设置一致
      - BOT_NAME=chatGpt
      # OpenAI API Key 支持负载均衡, 可以填写多个 Key 用逗号分隔
      - OPENAI_KEY=fastgpt-60lsm753wj0c2nzcn7u920b1-64f0c50f4e42523617d04d53
      # 服务器配置
      - HTTP_PORT=9000
      - HTTPS_PORT=9001
      - USE_HTTPS=false
      - CERT_FILE=cert.pem
      - KEY_FILE=key.pem
      # OpenAI 地址, 一般不需要修改, 除非你有自己的反向代理
      - API_URL=http://ai.newhopedairy.cn/
      # 代理设置, 例如 - HTTP_PROXY=http://127.0.0.1:7890, 默认代表不使用代理
      - HTTP_PROXY
